### ISSUE TITLE
Forcing rustler build using config doesn't work

### ISSUE THREAD

**Issue by Munksgaard** [adoptoposs/mjml_nif#151]
I'm building my elixir projects as a nix flake, which means that I cannot rely on rustler_precompiled. As suggested in the [documentation](https://hexdocs.pm/mjml/readme.html#installation) I tried disabling ruster_precompiled by putting the following in my config.exs (and adding rustler to my deps):

```elixir
config :rustler_precompiled, :force_build, mjml: true
```

However, it seems like [the explicit setting of force_build in native.ex](https://github.com/adoptoposs/mjml_nif/blob/main/lib/mjml/native.ex#L27) overrides this option.

**Comment by paulgoetze** [comment]
Hey @Munksgaard, thanks for creating this issue. I'll have a look!

**Comment by paulgoetze** [comment]
It seems to be a special case problem with the config priority in rustler_precompiled. 

:hourglass_flowing_sand: Waiting for more info about this in https://github.com/philss/rustler_precompiled/issues/80 …

**Comment by paulgoetze** [comment]
@Munksgaard A new version (v4.0.0) is published which fixes the issue with the config.
(Re the major version Bump: there should be no breaking changes, it just uses mrml v4.0+ and we sync with that.)
